/**
 * Core model-side game service.
 *
 * GameEngine coordinates game rules, time progression, enemy generation,
 * enemy attacks, and player actions. It is used by the controller, while
 * the UI remains focused on input and display.
 */
package game.engine;

import game.adapter.AttackOutcomeCalculator;
import game.adapter.AttackResolution;
import game.adapter.ChallengeDecisionAttackAdapter;
import game.buildings.Building;
import game.buildings.BuildingType;
import game.buildings.StorageBuilding;
import game.combat.VillageDefenseTestResult;
import game.exceptions.GameException;
import game.exceptions.InvalidActionException;
import game.exceptions.PopulationLimitExceededException;
import game.factory.BuildingFactory;
import game.factory.DefaultBuildingFactory;
import game.factory.DefaultInhabitantFactory;
import game.factory.InhabitantFactory;
import game.inhabitants.ArmyUnit;
import game.inhabitants.Inhabitant;
import game.inhabitants.InhabitantType;
import game.model.Player;
import game.model.Army;
import game.model.ResourceType;
import game.model.Village;
import game.persistence.GameState;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

public class GameEngine {
    private static final int DEFAULT_GUARD_HOURS = 3;

    private final Player player;
    private final TimeManager timeManager;
    private final DiceRoller diceRoller;
    private final VillageGenerator villageGenerator;
    private final ArmyGenerator armyGenerator;
    private final BuildingFactory buildingFactory;
    private final InhabitantFactory inhabitantFactory;
    private final AttackOutcomeCalculator attackCalculator;
    private final AtomicInteger nextId;
    private final List<String> pendingEvents;

    /**
     * Creates a brand-new game session with the default Assignment 3 setup.
     *
     * @param username the player username
     */
    public GameEngine(String username) {
        this(createNewState(username),
                new DefaultBuildingFactory(),
                new DefaultInhabitantFactory(),
                new ChallengeDecisionAttackAdapter());
    }

    /**
     * Creates a new game session using custom factories and attack logic.
     *
     * This constructor is useful for wiring the Assignment 3 factory
     * and adapter components from the controller layer.
     *
     * @param username the player username
     * @param buildingFactory the factory used to create buildings
     * @param inhabitantFactory the factory used to create inhabitants
     * @param attackCalculator the attack-resolution strategy
     */
    public GameEngine(String username,
                      BuildingFactory buildingFactory,
                      InhabitantFactory inhabitantFactory,
                      AttackOutcomeCalculator attackCalculator) {
        this(createNewState(username), buildingFactory, inhabitantFactory, attackCalculator);
    }

    /**
     * Restores a game engine from a previously saved game state.
     *
     * @param state the saved session state
     * @param buildingFactory the factory used by the engine
     * @param inhabitantFactory the factory used by the engine
     * @param attackCalculator the adapted attack calculator
     */
    public GameEngine(GameState state,
                      BuildingFactory buildingFactory,
                      InhabitantFactory inhabitantFactory,
                      AttackOutcomeCalculator attackCalculator) {
        this.player = new Player(state.getUsername(), state.getVillage());
        this.timeManager = new TimeManager(state.getTimeHours());
        this.diceRoller = new DiceRoller();
        this.buildingFactory = buildingFactory;
        this.inhabitantFactory = inhabitantFactory;
        this.attackCalculator = attackCalculator;
        this.villageGenerator = new VillageGenerator(diceRoller, buildingFactory, inhabitantFactory);
        this.armyGenerator = new ArmyGenerator(diceRoller, inhabitantFactory);
        this.nextId = new AtomicInteger(state.getNextInhabitantId());
        this.pendingEvents = new ArrayList<>();
    }

    public Player getPlayer() {
        return player;
    }

    public int getTime() {
        return timeManager.getHours();
    }

    /**
     * Creates a saveable snapshot of the current session.
     *
     * @return the current game state data
     */
    public GameState snapshot() {
        return new GameState(player.getUsername(), player.getVillage(), timeManager.getHours(), nextId.get());
    }

    /**
     * Returns and clears the pending event messages generated by the engine.
     *
     * @return the list of new event messages
     */
    public List<String> consumeEvents() {
        List<String> events = new ArrayList<>(pendingEvents);
        pendingEvents.clear();
        return events;
    }

    /**
     * Advances the game one hour at a time.
     *
     * Each hour may trigger resource collection, guard countdown,
     * and a possible random enemy attack.
     *
     * @param hours the number of hours to advance
     */
    public void advanceTime(int hours) {
        for (int i = 0; i < hours; i++) {
            timeManager.advanceHours(1);
            player.getVillage().collectResources();
            player.getVillage().advanceGuardTime(1);
            maybeTriggerEnemyAttack();
        }
    }

    /**
     * Builds a new structure using the configured building factory.
     *
     * @param type the type of building requested
     * @throws GameException if the build action is invalid or unaffordable
     */
    public void build(BuildingType type) throws GameException {
        if (type == BuildingType.VILLAGE_HALL) {
            throw new InvalidActionException("Village Hall already exists.");
        }
        if (!player.getVillage().canBuildMore()) {
            throw new InvalidActionException("Building limit reached for this village.");
        }
        Building building = buildingFactory.create(type);
        player.getVillage().getResources().spendAll(building.getBuildCost());
        player.getVillage().addBuilding(building);
        advanceTime(1);
        pendingEvents.add(building.getName() + " construction completed.");
    }

    /**
     * Trains a new inhabitant or combat unit using the inhabitant factory.
     *
     * @param type the inhabitant type to train
     * @throws GameException if training fails
     */
    public void train(InhabitantType type) throws GameException {
        ensurePopulationSpace();
        Map<ResourceType, Integer> cost = getTrainingCost(type);
        player.getVillage().getResources().spendAll(cost);

        Inhabitant inhabitant = inhabitantFactory.create(type, nextId.getAndIncrement());
        player.getVillage().addInhabitant(inhabitant);
        if (inhabitant instanceof ArmyUnit armyUnit) {
            player.getVillage().getArmy().addUnit(armyUnit);
        }

        int trainingHours = type == InhabitantType.CATAPULT ? 2 : 1;
        advanceTime(trainingHours);
        pendingEvents.add(inhabitant.getName() + " training completed.");
    }

    public void trainWorker() throws GameException {
        train(InhabitantType.WORKER);
    }

    public void trainMiner() throws GameException {
        train(InhabitantType.MINER);
    }

    public void trainCollector() throws GameException {
        train(InhabitantType.COLLECTOR);
    }

    public void trainSoldier() throws GameException {
        train(InhabitantType.SOLDIER);
    }

    public void trainArcher() throws GameException {
        train(InhabitantType.ARCHER);
    }

    public void trainKnight() throws GameException {
        train(InhabitantType.KNIGHT);
    }

    public void trainCatapult() throws GameException {
        train(InhabitantType.CATAPULT);
    }

    /**
     * Upgrades the selected building and updates storage capacity when needed.
     *
     * @param index the index of the building to upgrade
     * @throws GameException if the upgrade fails
     */
    public void upgradeBuilding(int index) throws GameException {
        List<Building> buildings = player.getVillage().getBuildings();
        if (index < 0 || index >= buildings.size()) {
            throw new InvalidActionException("Invalid building index.");
        }
        Building building = buildings.get(index);
        building.upgrade(player.getVillage().getResources());
        if (building instanceof StorageBuilding storageBuilding) {
            int currentCapacity = player.getVillage().getResources().getCapacity(storageBuilding.getResourceType());
            player.getVillage().getResources().setCapacity(storageBuilding.getResourceType(), currentCapacity + 100);
        }
        advanceTime(1);
        pendingEvents.add(building.getName() + " upgraded to level " + building.getLevel() + ".");
    }

    public void upgradeInhabitant(int index) throws GameException {
        List<Inhabitant> inhabitants = player.getVillage().getInhabitants();
        if (index < 0 || index >= inhabitants.size()) {
            throw new InvalidActionException("Invalid inhabitant index.");
        }
        Inhabitant inhabitant = inhabitants.get(index);
        inhabitant.upgrade(player.getVillage().getResources());
        advanceTime(1);
        pendingEvents.add(inhabitant.getName() + "#" + inhabitant.getId() + " upgraded to level " + inhabitant.getLevel() + ".");
    }

    /**
     * Generates enemy villages appropriate for the player's current progress.
     *
     * @return the villages available to attack
     */
    public List<Village> exploreVillages() {
        int playerLevel = Math.max(1, player.getVillage().getTrophies() / 100 + 1);
        return new ArrayList<>(villageGenerator.generateVillages(playerLevel));
    }

    /**
     * Generates a detached testing army compatible with the player's current level.
     *
     * @return the generated testing army
     */
    public Army generateTestingArmy() {
        int playerLevel = Math.max(1, player.getVillage().getTrophies() / 100 + 1);
        return armyGenerator.generateArmy(playerLevel);
    }

    /**
     * Tests the player's village against a series of compatible generated armies.
     *
     * @param numberOfTests the number of generated attacks to simulate
     * @return the final defense test result
     */
    public VillageDefenseTestResult testVillageDefense(int numberOfTests) {
        int playerLevel = Math.max(1, player.getVillage().getTrophies() / 100 + 1);
        List<Army> armies = armyGenerator.generateArmies(playerLevel, Math.max(1, numberOfTests));
        int successfulDefenses = 0;
        List<String> rounds = new ArrayList<>();

        for (int i = 0; i < armies.size(); i++) {
            Army generatedArmy = armies.get(i);
            Village attacker = new Village(1000 + i, "TestArmy" + (i + 1));
            for (ArmyUnit unit : generatedArmy.getUnits()) {
                attacker.addInhabitant(unit);
                attacker.getArmy().addUnit(unit);
            }

            AttackResolution resolution = attackCalculator.resolve(attacker, player.getVillage());
            boolean defended = !resolution.isSuccess();
            if (defended) {
                successfulDefenses++;
            }
            rounds.add("Round " + (i + 1) + ": enemy attack score="
                    + generatedArmy.calculateAttackScore() + " -> "
                    + (defended ? "Defense Held" : "Defense Failed"));
        }

        int totalTests = armies.size();
        return new VillageDefenseTestResult(totalTests, successfulDefenses, totalTests - successfulDefenses, rounds);
    }

    /**
     * Resolves an attack using the configured attack adapter.
     *
     * The adapter delegates the combat outcome to the provided external API,
     * then the engine applies trophies, loot, guard time, and event messages.
     *
     * @param enemyVillage the selected enemy village
     * @return the final attack result shown to the player
     * @throws GameException if the attack is not allowed
     */
    public game.combat.AttackResult attack(Village enemyVillage) throws GameException {
        if (enemyVillage.isGuardActive()) {
            throw new InvalidActionException("This village is currently under guard protection.");
        }
        if (player.getVillage().getArmy().size() == 0) {
            throw new InvalidActionException("Train army units before attacking another village.");
        }

        AttackResolution resolution = attackCalculator.resolve(player.getVillage(), enemyVillage);
        int trophies = resolution.isSuccess() ? 20 : -10;

        if (resolution.isSuccess()) {
            applyLoot(player.getVillage(), resolution.getLootGold(), resolution.getLootIron(), resolution.getLootWood(), false);
        }
        player.getVillage().addTrophies(trophies);
        enemyVillage.activateGuard(DEFAULT_GUARD_HOURS);

        advanceTime(1);
        pendingEvents.add("Attack on " + enemyVillage.getName() + (resolution.isSuccess() ? " succeeded." : " failed."));
        return new game.combat.AttackResult(
                resolution.isSuccess(),
                resolution.getLootGold(),
                resolution.getLootIron(),
                resolution.getLootWood(),
                trophies
        );
    }

    /**
     * Randomly triggers an enemy attack when the player's village
     * is outside of the guard period.
     */
    private void maybeTriggerEnemyAttack() {
        Village village = player.getVillage();
        if (village.isGuardActive()) {
            return;
        }
        if (!diceRoller.chance(0.15)) {
            return;
        }

        Village enemy = villageGenerator.generateVillages(Math.max(1, village.getTrophies() / 100 + 1)).get(0);
        AttackResolution resolution = attackCalculator.resolve(enemy, village);
        if (resolution.isSuccess()) {
            applyLoot(village, resolution.getLootGold(), resolution.getLootIron(), resolution.getLootWood(), true);
            village.addTrophies(-15);
            pendingEvents.add("Enemy raid succeeded. Lost " + resolution.getLootGold() + " gold, "
                    + resolution.getLootIron() + " iron, and " + resolution.getLootWood() + " wood.");
        } else {
            village.addTrophies(10);
            pendingEvents.add("Your village defended an enemy attack.");
        }
        village.activateGuard(DEFAULT_GUARD_HOURS);
    }

    /**
     * Applies loot gain or loot loss to a village.
     *
     * @param village the village receiving the resource change
     * @param gold the gold amount
     * @param iron the iron amount
     * @param wood the wood amount
     * @param subtract true when resources are being stolen from the village
     */
    private void applyLoot(Village village, int gold, int iron, int wood, boolean subtract) {
        if (subtract) {
            village.getResources().set(ResourceType.GOLD, Math.max(0, village.getResources().get(ResourceType.GOLD) - gold));
            village.getResources().set(ResourceType.IRON, Math.max(0, village.getResources().get(ResourceType.IRON) - iron));
            village.getResources().set(ResourceType.WOOD, Math.max(0, village.getResources().get(ResourceType.WOOD) - wood));
        } else {
            village.getResources().add(ResourceType.GOLD, gold);
            village.getResources().add(ResourceType.IRON, iron);
            village.getResources().add(ResourceType.WOOD, wood);
        }
    }

    /**
     * Returns the resource cost map for training each inhabitant type.
     *
     * @param type the inhabitant type
     * @return the resource cost required for training
     */
    private Map<ResourceType, Integer> getTrainingCost(InhabitantType type) {
        Map<ResourceType, Integer> cost = new EnumMap<>(ResourceType.class);
        switch (type) {
            case WORKER -> cost.put(ResourceType.GOLD, 20);
            case MINER, COLLECTOR -> cost.put(ResourceType.GOLD, 15);
            case SOLDIER -> cost.put(ResourceType.GOLD, 30);
            case ARCHER -> {
                cost.put(ResourceType.GOLD, 35);
                cost.put(ResourceType.WOOD, 10);
            }
            case KNIGHT -> {
                cost.put(ResourceType.GOLD, 50);
                cost.put(ResourceType.IRON, 20);
            }
            case CATAPULT -> {
                cost.put(ResourceType.GOLD, 60);
                cost.put(ResourceType.WOOD, 20);
                cost.put(ResourceType.IRON, 15);
            }
        }
        return cost;
    }

    private void ensurePopulationSpace() throws PopulationLimitExceededException {
        if (!player.getVillage().hasPopulationSpace()) {
            throw new PopulationLimitExceededException("No population space. Build or upgrade farms.");
        }
    }

    /**
     * Creates the default starting state for a brand-new game.
     *
     * @param username the player username
     * @return the initial game state
     */
    private static GameState createNewState(String username) {
        BuildingFactory buildingFactory = new DefaultBuildingFactory();
        InhabitantFactory inhabitantFactory = new DefaultInhabitantFactory();

        Village village = new Village(1, username + "'s Village");
        village.addBuilding(buildingFactory.create(BuildingType.VILLAGE_HALL));
        village.addBuilding(buildingFactory.create(BuildingType.FARM));
        village.addBuilding(buildingFactory.create(BuildingType.LUMBER_MILL));
        village.addBuilding(buildingFactory.create(BuildingType.GOLD_MINE));
        village.addBuilding(buildingFactory.create(BuildingType.IRON_MINE));
        village.getResources().add(ResourceType.GOLD, 200);
        village.getResources().add(ResourceType.IRON, 150);
        village.getResources().add(ResourceType.WOOD, 200);

        Inhabitant startingWorker = inhabitantFactory.create(InhabitantType.WORKER, 1);
        village.addInhabitant(startingWorker);
        return new GameState(username, village, 0, 2);
    }
}
